Replaced win32yank with clip; scripts exit on error

diff --git a/misc/opi b/misc/opi
--- a/misc/opi
+++ b/misc/opi
@@ -1,30 +1,38 @@
 #!/usr/bin/env bash
-eval $(op signin my)
 
-ENTRY=$(op list items | jq -c '.[] | {title: (.overview.title), url: (.overview.url), uuid: (.uuid)}' | fzf)
+set -e
 
 OS=$(uname -a | tr '[:lower:]' '[:upper:]')
 MAC='DARWIN'
 LINUX='LINUX'
 WSL='MICROSOFT'
 
-if [ ! -z "$ENTRY" ]; then
-	ITEM_ID=$(echo $ENTRY | jq '.uuid' | tr -d '"')
+SIGNIN=$(op signin my)
+eval "$SIGNIN"
+
+ENTRY=$(op list items | jq -c '.[] | {title: (.overview.title), url: (.overview.url), uuid: (.uuid)}' | fzf)
+
+if [ -n "$ENTRY" ]; then
+	ITEM_ID=$(echo "$ENTRY" | jq '.uuid' | tr -d '"')
 	ITEM=$(op get item "$ITEM_ID" --fields title,url,username,password)
 
 	case $OS in
 	*$MAC*)
-		echo $ITEM | jq '.password' | tr -d '"' | pbcopy
+		echo "$ITEM" | jq '.password' | tr -d '"' | pbcopy
 		;;
 	*$LINUX*)
 		if [[ $OS =~ $WSL ]]; then
-			echo $ITEM | jq '.password' | tr -d '"' | win32yank.exe -i
+			echo "$ITEM" | jq '.password' | tr -d '"' | clip.exe
 		else
-			echo $ITEM | jq '.password' | tr -d '"' | xclip -selection -c
+			echo "$ITEM" | jq '.password' | tr -d '"' | xclip -selection -c
 		fi
+		;;
+	*)
+		>&2 echo "Unable to detect OS to determine clipboard executable"
+		exit 1
 		;;
 	esac
 
 	echo "Copied password to clipboard!"
-	echo $ITEM | jq '. | {title: (.title), url: (.url), username: (.username), password: "*****"}'
+	echo "$ITEM" | jq '. | {title: (.title), url: (.url), username: (.username), password: "*****"}'
 fi
diff --git a/misc/opt b/misc/opt
--- a/misc/opt
+++ b/misc/opt
@@ -1,31 +1,38 @@
 #!/usr/bin/env bash
 
-eval $(op signin my)
+set -e
 
 OS=$(uname -a | tr '[:lower:]' '[:upper:]')
 MAC='DARWIN'
 LINUX='LINUX'
 WSL='MICROSOFT'
 
+SIGNIN=$(op signin my)
+eval "$SIGNIN"
+
 ENTRY=$(op list items | jq -c '.[] | {title: (.overview.title), url: (.overview.url), uuid: (.uuid)}' | fzf)
 
-if [ ! -z "$ENTRY" ]; then
-	ITEM=$(echo $ENTRY | jq '.uuid' | tr -d '"')
+if [ -n "$ENTRY" ]; then
+	ITEM=$(echo "$ENTRY" | jq '.uuid' | tr -d '"')
 	TOKEN=$(op get totp "$ITEM")
 
 	case $OS in
 	*$MAC*)
-		echo $TOKEN | pbcopy
+		echo "$TOKEN" | pbcopy
 		;;
 	*$LINUX*)
 		if [[ $OS =~ $WSL ]]; then
-			echo $TOKEN | win32yank.exe -i
+			echo "$TOKEN" | clip.exe
 		else
-			echo $TOKEN | xclip -selection -c
+			echo "$TOKEN" | xclip -selection -c
 		fi
+		;;
+	*)
+		>&2 echo "Unable to detect OS to determine clipboard executable"
+		exit 1
 		;;
 	esac
 
 	echo "Copied token to clipboard!"
-	echo $ENTRY | jq '. | {title: (.title), url: (.url), token: "****"}'
+	echo "$ENTRY" | jq '. | {title: (.title), url: (.url), token: "****"}'
 fi
