Fixed mac bs, added tabs, fixed gruvbox colors

diff --git a/zsh/zshenv b/zsh/zshenv
--- a/zsh/zshenv
+++ b/zsh/zshenv
@@ -5,29 +5,29 @@ local MAC='Darwin'
 local LINUX='Linux'
 
 case $OS in
-  *$MAC*)
-    alias ls='ls -G'
-    alias copy='pbcopy'
-    alias ctags=/usr/local/opt/universal-ctags/bin/ctags
+*$MAC*)
+	alias ls='ls -G'
+	alias copy='pbcopy'
+	alias ctags=/usr/local/opt/universal-ctags/bin/ctags
 	export PATH=$PATH:/usr/local/bin
 	export JAVA_HOME=$(/usr/libexec/java_home)
 	export GOROOT=/usr/local/opt/go/libexec
-    ;;
-  *$LINUX*)
-    alias copy='xclip -selection -c'
-    alias ls='ls --color=auto'
-    alias fd='fdfind'
-    alias bat='batcat'
+	;;
+*$LINUX*)
+	alias copy='xclip -selection -c'
+	alias ls='ls --color=auto'
+	alias fd='fdfind'
+	alias bat='batcat'
 	export JAVA_HOME=/opt/java/zulu8.52.0.24-sa-jdk8.0.282
 	export GRADLE_HOME=/opt/gradle/6.8.3
 	export GOROOT=/opt/go
-    ;;
+	;;
 esac
 
 alias luamake=/Users/asidlo/.local/src/lua-language-server/3rd/luamake/luamake
 
 if (( $+commands[tree] )); then
-  alias tree='tree -C'
+	alias tree='tree -C'
 fi
 
 alias ll='ls -AlFG'
@@ -38,20 +38,16 @@ alias cls='clear'
 alias nnn='nnn -de'
 
 if (( $+commands[nvim] )); then
-  export VISUAL=nvim
-  export EDITOR=nvim
-  export MANPAGER="$EDITOR +Man!"
+	export VISUAL=nvim
+	export EDITOR=nvim
+	export MANPAGER="$EDITOR +Man!"
 else
-  export VISUAL=vim
-  export EDITOR=vim
-  export MANPAGER="vim -M +MANPAGER -"
+	export VISUAL=vim
+	export EDITOR=vim
+	export MANPAGER="vim -M +MANPAGER -"
 fi
 
 export MANWIDTH=999
-
-export NNN_PLUG='o:fzopen;c:fzcd;p:preview-tui'
-export NNN_FCOLORS='c1e2042e006033f7c6d6abc4'
-export NNN_FIFO='/tmp/nnn.fifo'
 
 export GOPATH=$HOME/.local/go
 export PATH=$PATH:$GOROOT/bin
@@ -64,33 +60,33 @@ export PATH=$PATH:~/.local/bin
 
 # Fd, bat, fzf
 if [[ $OS =~ $LINUX ]]; then
-  FD_EXE='fdfind'
-  BAT_EXE='batcat'
+	FD_EXE='fdfind'
+	BAT_EXE='batcat'
 else
-  FD_EXE='fd'
-  BAT_EXE='bat'
+	FD_EXE='fd'
+	BAT_EXE='bat'
 fi
 
 if (( $+commands[$FD_EXE] )) && (( $+commands[fzf] )) && (( $+commands[$BAT_EXE] )); then
-  export FD_OPTS='--follow --exclude .git --exclude node_modules --exclude "*.class"'
-  export FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard 2> /dev/null | $FD_EXE --type f --type l $FD_OPTS"
-  export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
-  export FZF_ALT_C_COMMAND="$FD_EXE --type d $FD_OPTS"
-  export FZF_DEFAULT_OPTS="
-    --color=fg:#c2bebe,bg:-1,hl:#8be9fd
-    --color=fg+:#f8f8f2,bg+:-1,hl+:#ff79c6
-    --color=info:#bd93f9,prompt:#ff79c6,pointer:#ff79c6
-    --color=marker:#50fa7b,spinner:#8be9fd,header:#f1fa8c
-    --height 50% -1 --reverse --multi --inline-info
-    --preview='$BAT_EXE --color=always --style=numbers {}'
-    --preview-window='right:hidden'
-    --bind='F2:toggle-preview'
-    --bind='ctrl-d:half-page-down'
-    --bind='ctrl-u:half-page-up'
-    --bind='ctrl-a:select-all+accept'
-  "
+	export FD_OPTS='--follow --exclude .git --exclude node_modules --exclude "*.class"'
+	export FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard 2> /dev/null | $FD_EXE --type f --type l $FD_OPTS"
+	export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
+	export FZF_ALT_C_COMMAND="$FD_EXE --type d $FD_OPTS"
+	export FZF_DEFAULT_OPTS="
+	--color=fg:#c2bebe,bg:-1,hl:#8be9fd
+	--color=fg+:#f8f8f2,bg+:-1,hl+:#ff79c6
+	--color=info:#bd93f9,prompt:#ff79c6,pointer:#ff79c6
+	--color=marker:#50fa7b,spinner:#8be9fd,header:#f1fa8c
+	--height 50% -1 --reverse --multi --inline-info
+	--preview='$BAT_EXE --color=always --style=numbers {}'
+	--preview-window='right:hidden'
+	--bind='F2:toggle-preview'
+	--bind='ctrl-d:half-page-down'
+	--bind='ctrl-u:half-page-up'
+	--bind='ctrl-a:select-all+accept'
+	"
 else
-  >&2 echo "$fg[yellow]WARN$reset_color: [fzf|$FD_EXE|$BAT_EXE]+ not found. Install all and add to PATH" 
+	>&2 echo "$fg[yellow]WARN$reset_color: [fzf|$FD_EXE|$BAT_EXE]+ not found. Install all and add to PATH" 
 fi
 
 [ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"
